displayName=Group Item Tracker
author=Cody Lyttle
description=Track items that belong in group ironman shared storage.
tags=gim,group,share,storage,track
plugins=com.groupitemtracker.GroupItemTrackerPlugin