displayName=Group Item Tracker
author=C.L
description=Keeps track of items that belong in group storage.
tags=gim,group,iron,item,share,storage,track
plugins=com.groupitemtracker.GroupItemTrackerPlugin
build=standard